---
title: "Resume"
---

# **Avery Eastman** 

Fort Collins, CO \| 503-839-0802 \| [avery.eastman\@icloud.com](mailto:avery.eastman@icloud.com) \| <https://www.linkedin.com/in/avery-eastman>

[**SUMMARY:**]{.underline} 

I am a third-year undergraduate, emerging in environmental management and conservation science. I am keen to apply my knowledge of earth systems and sustainability science to real world applications. I hope to gain fieldwork and research experience to further my knowledge, skills and to build a professional network. My core competencies include: 

-   Experience with ArcGIS tools and Excel 

<!-- -->

-   Organized and diligent worker, with the ability to analyze and interpret data  

[**EDUCATION:**]{.underline} 

**Ecosystem Science and Sustainability,** May 2026

*Colorado State University*, Fort Collins, Colorado, GPA 3.60

[**OUTDOOR AND SALES EXPERIENCE:**]{.underline}

**Climbing Wall Assistant**, *Colorado State University: Campus Recreation*, May 2024–Present

Fort Collins, CO

-   Fostered an encouraging and inclusive environment for all patrons 
-   Led belay lessons and taught climbing classes 
-   Collaborated with other staff to set routes and bouldering problems  

**Sales Associate: Women’s Apparel**, *Nordstrom*, Summer 2023

Portland, OR

-   Utilized outstanding interpersonal skills and product knowledge to address customers’ concerns and questions
-   Processed payments, returns, and exchanges
-   Organized and advertised apparel to increase sales

**Rock Climbing Summer Camp Instructor/Gym Staff**, *Multnomah Athletic Club*, Summer 2022

Portland, OR

-   Created and led fun and engaging activities for kids ages 4-12 years old
-   Analyzed and evaluated potential risk factors to assure the safety of all individuals in the gym
-   Oriented individuals to the gym, including check-in procedures and informing them of the gym rules

**Head Lifeguard**, *Oswego Lake Country Club*, Summer 2021

Lake Oswego, OR

-   Managed a team of 14 lifeguards and trained 9 new lifeguards due to extensive experience and knowledge about the job
-   Handled communication, such as comments, concerns, and questions, with member
-   Ensured the safety of all patrons by enforcing safety protocols and assessing and responding to incidents
-   Received a raise after less than a year in the position 

[**COMMUNITY ENGAGEMENT:**]{.underline}

**Center for Public Deliberation**, *Colorado State University*, Spring 2024

Fort Collins, CO 

-   Facilitate group discussions for 6-10 people to help guide participants through tough issues containing strong tensions
-   Engaged with various stakeholders to achieve collaborative problem solving
